version: 2.1

commands:
    install-mapbox-token:
         steps:
             - run:
                 name: Install Mapbox Access Token
                 command: echo "foo" > ~/.mapbox

    restore-cache:
         steps:
             - restore_cache:
                 name: Restore cache
                 keys:
                    - carthage-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cartfile.resolved" }}

    save-cache:
        steps:
             - save_cache:
                 key: carthage-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Cartfile.resolved" }}
                 paths:
                     - Carthage
                     - Cartfile.resolved

    install-carthage:
        steps:
            - run:
                name: Install Carthage
                command: |
                    curl -OL "https://github.com/Carthage/Carthage/releases/download/0.38.0/Carthage.pkg"
                    sudo installer -pkg Carthage.pkg -target /

    publish-codecov:
        steps:
            - run:
                name: Publish Code Coverage
                command: bash <(curl -s https://codecov.io/bash)
    carthage-bootstrap:
        steps:
            - run:
                name: Dependencies
                command: carthage bootstrap --platform all --cache-builds --configuration Debug --use-xcframeworks   

jobs:
  spm-linux-job:
    docker:
      - image: swift:5.4
    steps:
      - checkout
      # Limiting number of parallel jobs to avoid build crash bug.
      - run: swift build --jobs=1
      - run: swift test

  spm-job:
    parameters:
      xcode:
        type: string
    macos:
      xcode: << parameters.xcode >>
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: swift build
  
  carthage-integration-test:
    parameters:
      xcode:
        type: string
    macos:
      xcode: << parameters.xcode >>
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - install-mapbox-token
      - install-carthage
      - run:
          name: "Create integration Cartfile"
          command: |
            echo 'github "track-asia/trackasia-directions-swift"' \"$CIRCLE_SHA1\" > Cartfile 
      - run:
          name: "Build"
          command: |
            carthage bootstrap --platform all --use-netrc --use-xcframeworks
  example-app-build:
    macos:
      xcode: "12.4.0"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - install-mapbox-token
      - install-carthage
      - restore-cache
      - carthage-bootstrap
      - run:
          name: "Build example app"
          command: xcodebuild -sdk iphonesimulator -project MapboxDirections.xcodeproj -scheme 'Example' -destination 'platform=iOS Simulator,OS=14.4,name=iPhone 12 Pro Max' clean build
      - save-cache

  build-job:
    parameters:
      xcode:
        type: string
      device:
        type: string
        default: "iPhone 8 Plus"
      iOS:
        type: string
        default: "12.1"
      watchOS:
        type: string
        default: "5.0"
      tvOS:
        type: string
        default: "12.0"
      test:
        type: boolean
        default: true
      codecoverage:
        type: boolean
        default: false
    macos:
      xcode: << parameters.xcode >>
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - install-mapbox-token
      - install-carthage
      - restore-cache
      - run:
          name: Install prerequisites
          command: |
            if [ $(xcversion simulators | grep -cF "iOS << parameters.iOS >> Simulator (installed)") -eq 0 ]; then xcversion simulators --install="iOS << parameters.iOS >>" || true; fi
      - carthage-bootstrap
      - run:
          name: iOS
          command: xcodebuild -sdk iphonesimulator -project MapboxDirections.xcodeproj -scheme 'MapboxDirections iOS' -destination 'platform=iOS Simulator,OS=<< parameters.iOS >>,name=<< parameters.device >>' clean build <<# parameters.test >>test<</ parameters.test >><<# parameters.codecoverage >> -enableCodeCoverage "YES"<</ parameters.codecoverage >>
      - when:
          condition: << parameters.codecoverage >>
          steps:
            - publish-codecov
      - run:
          name: tvOS
          command: xcodebuild -project MapboxDirections.xcodeproj -scheme 'MapboxDirections tvOS' -destination 'platform=tvOS Simulator,name=Apple TV 4K (at 1080p),OS=<< parameters.tvOS >>' clean build <<# parameters.test >>test <</ parameters.test >> <<# parameters.codecoverage >>-enableCodeCoverage YES<</ parameters.codecoverage >>
      - when:
          condition: << parameters.codecoverage >>
          steps:
            - publish-codecov
      - run:
          name: macOS
          command: xcodebuild -project MapboxDirections.xcodeproj -scheme 'MapboxDirections Mac' clean build<<# parameters.test >> test <</ parameters.test >><<# parameters.codecoverage >>-enableCodeCoverage YES<</ parameters.codecoverage >>
      - run:
          name: watchOS
          command: xcodebuild -project MapboxDirections.xcodeproj -scheme 'MapboxDirections watchOS' -destination 'platform=watchOS Simulator,name=Apple Watch Series 5 - 44mm,OS=<< parameters.watchOS >>' clean build
      - save-cache

workflows:
  workflow:
    jobs:
      - build-job:
          name: "Dev Build: Xcode 12.0"
          xcode: "12.0.0"
          iOS: "14.0"
          tvOS: "14.0"
          watchOS: "7.0"
      - carthage-integration-test:
          name: "Carthage Integration Test 12.0"
          xcode: "12.0.0"
      - carthage-integration-test:
          name: "Carthage Integration Test 12.4"
          xcode: "12.4.0"
      - spm-job:
          name: "SPM build 12.0.0"
          xcode: "12.0.0"
      - spm-job:
          name: "SPM build 12.4.0"
          xcode: "12.4.0"
      - spm-linux-job:
          name: "SPM Ubuntu build"
      - example-app-build:
          name: "Build example app"
